name: Automatic Data Preprocessing

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Preprocessing
        run: |
          cd preprocessing
          python automate_SheloRahmaSari.py

      - name: Upload Processed Dataset
        uses: actions/upload-artifact@v4
        with:
          name: telco_clean
          path: preprocessing/dataset_preprocessing/telco_clean.csv